import { describe, expect, it } from 'vitest'
import { canAccessSidebarRoute, canShowSidebarItem } from './sidebar-access'

describe('sidebar role access', () => {
  it('keeps staff focused on support work only', () => {
    expect(canShowSidebarItem('/support', 'staff')).toBe(true)
    expect(canShowSidebarItem('/chats', 'staff')).toBe(true)
    expect(canShowSidebarItem('/internal-chat', 'staff')).toBe(true)
    expect(canShowSidebarItem('/friends', 'staff')).toBe(true)
    expect(canShowSidebarItem('/manuals', 'staff')).toBe(true)
    expect(canShowSidebarItem('/notifications', 'staff')).toBe(true)
    expect(canShowSidebarItem('/notification-settings', 'staff')).toBe(false)
    expect(canShowSidebarItem('/escalations', 'staff')).toBe(true)
    expect(canShowSidebarItem('/escalations', 'staff', { staffName: '田島' })).toBe(true)

    expect(canShowSidebarItem('/', 'staff')).toBe(false)
    expect(canShowSidebarItem('/broadcasts', 'staff')).toBe(false)
    expect(canShowSidebarItem('/templates', 'staff')).toBe(false)
    expect(canShowSidebarItem('/automations', 'staff')).toBe(false)
    expect(canShowSidebarItem('/form-submissions', 'staff')).toBe(false)
    expect(canShowSidebarItem('/accounts', 'staff')).toBe(false)
    expect(canShowSidebarItem('/staff', 'staff')).toBe(false)
  })

  it('keeps secondary-only staff out of LINE chat and customer management screens', () => {
    expect(canShowSidebarItem('/escalations', 'secondary')).toBe(true)
    expect(canShowSidebarItem('/escalations', 'secondary', { staffName: '松山' })).toBe(true)
    expect(canShowSidebarItem('/chats', 'secondary', { staffName: '松山' })).toBe(false)
    expect(canShowSidebarItem('/support', 'secondary', { staffName: '松山' })).toBe(false)
    expect(canShowSidebarItem('/friends', 'secondary', { staffName: '松山' })).toBe(false)
    expect(canShowSidebarItem('/internal-chat', 'secondary', { staffName: '松山' })).toBe(true)
    expect(canShowSidebarItem('/notifications', 'secondary', { staffName: '松山' })).toBe(true)
    expect(canShowSidebarItem('/manuals', 'secondary', { staffName: '松山' })).toBe(true)
    expect(canShowSidebarItem('/notification-settings', 'secondary', { staffName: '松山' })).toBe(false)

    expect(canAccessSidebarRoute('/escalations', 'secondary')).toBe(true)
    expect(canAccessSidebarRoute('/escalations/detail', 'secondary')).toBe(true)
    expect(canAccessSidebarRoute('/chats', 'secondary')).toBe(false)
    expect(canAccessSidebarRoute('/support', 'secondary')).toBe(false)
    expect(canAccessSidebarRoute('/friends', 'secondary')).toBe(false)
    expect(canAccessSidebarRoute('/manuals', 'secondary')).toBe(true)
    expect(canAccessSidebarRoute('/staff', 'secondary')).toBe(false)
  })

  it('keeps sensitive management controls owner-only while preserving admin operations', () => {
    expect(canShowSidebarItem('/staff', 'owner')).toBe(true)
    expect(canShowSidebarItem('/staff', 'admin')).toBe(false)
    expect(canShowSidebarItem('/health', 'owner')).toBe(true)
    expect(canShowSidebarItem('/health', 'admin')).toBe(true)
    expect(canShowSidebarItem('/emergency', 'owner')).toBe(true)
    expect(canShowSidebarItem('/emergency', 'admin')).toBe(false)
    expect(canShowSidebarItem('/accounts', 'owner')).toBe(true)
    expect(canShowSidebarItem('/accounts', 'admin')).toBe(false)
    expect(canShowSidebarItem('/notification-settings', 'admin')).toBe(true)
    expect(canShowSidebarItem('/pools', 'admin')).toBe(true)
    expect(canShowSidebarItem('/users', 'admin')).toBe(true)
    expect(canShowSidebarItem('/updates', 'admin')).toBe(true)
    expect(canShowSidebarItem('/broadcasts', 'admin')).toBe(false)
    expect(canShowSidebarItem('/scenarios', 'owner')).toBe(false)
    expect(canShowSidebarItem('/auto-replies', 'owner')).toBe(false)
    expect(canShowSidebarItem('/friend-add-settings', 'owner')).toBe(false)
  })

  it('does not hide owner/admin menus before the cached role is loaded', () => {
    expect(canShowSidebarItem('/accounts', null)).toBe(false)
    expect(canShowSidebarItem('/broadcasts', undefined)).toBe(false)
    expect(canShowSidebarItem('/escalations', null)).toBe(false)
    expect(canShowSidebarItem('/staff', '')).toBe(false)
    expect(canShowSidebarItem('/health', null)).toBe(true)
    expect(canShowSidebarItem('/emergency', null)).toBe(false)
  })

  it('redirects staff away from management routes while allowing support routes', () => {
    expect(canAccessSidebarRoute('/support', 'staff')).toBe(true)
    expect(canAccessSidebarRoute('/support/case-1', 'staff')).toBe(true)
    expect(canAccessSidebarRoute('/chats', 'staff')).toBe(true)
    expect(canAccessSidebarRoute('/internal-chat', 'staff')).toBe(true)
    expect(canAccessSidebarRoute('/notifications', 'staff')).toBe(true)
    expect(canAccessSidebarRoute('/notification-settings', 'staff')).toBe(false)

    expect(canAccessSidebarRoute('/', 'staff')).toBe(false)
    expect(canAccessSidebarRoute('/broadcasts', 'staff')).toBe(false)
    expect(canAccessSidebarRoute('/accounts', 'staff')).toBe(false)
    expect(canAccessSidebarRoute('/staff', 'staff')).toBe(false)

    expect(canAccessSidebarRoute('/broadcasts', 'owner')).toBe(false)
    expect(canAccessSidebarRoute('/broadcasts', 'admin')).toBe(false)
    expect(canAccessSidebarRoute('/broadcasts', null)).toBe(false)
    expect(canAccessSidebarRoute('/notifications', 'owner')).toBe(true)
    expect(canAccessSidebarRoute('/notifications', 'admin')).toBe(true)
    expect(canAccessSidebarRoute('/broadcasts/broadcast-1', 'owner')).toBe(false)
    expect(canAccessSidebarRoute('/scenarios', 'owner')).toBe(false)
    expect(canAccessSidebarRoute('/scenarios/detail', 'owner')).toBe(false)
    expect(canAccessSidebarRoute('/auto-replies', 'owner')).toBe(false)
    expect(canAccessSidebarRoute('/friend-add-settings', 'owner')).toBe(false)
  })

  it('keeps sensitive management routes owner-only even when opened directly', () => {
    expect(canAccessSidebarRoute('/staff', 'owner')).toBe(true)
    expect(canAccessSidebarRoute('/staff', 'admin')).toBe(false)
    expect(canAccessSidebarRoute('/staff', 'staff')).toBe(false)
    expect(canAccessSidebarRoute('/staff/member-1', 'admin')).toBe(false)
    expect(canAccessSidebarRoute('/staff/member-1', 'owner')).toBe(true)
    expect(canAccessSidebarRoute('/health', 'owner')).toBe(true)
    expect(canAccessSidebarRoute('/health', 'admin')).toBe(true)
    expect(canAccessSidebarRoute('/health/account-1', 'admin')).toBe(true)
    expect(canAccessSidebarRoute('/accounts', 'owner')).toBe(true)
    expect(canAccessSidebarRoute('/accounts', 'admin')).toBe(false)
    expect(canAccessSidebarRoute('/accounts/account-1', 'admin')).toBe(false)
    expect(canAccessSidebarRoute('/emergency', 'owner')).toBe(true)
    expect(canAccessSidebarRoute('/emergency', 'admin')).toBe(false)
  })
})
